### PR TITLE
Update shopui.php

### PR DESCRIPTION
**Pull request by esh123cookie**

### CODE REVIEW

**Comment by Todo56** [comment]
You can edit the plugin to change the command on your own.

**Comment by esh123cookie** [comment]
> You can edit the plugin to change the command on your own.

i dont want to take your credit

**Comment by Todo56** [comment]
I know, it just doesn't make sense to change the command without changing the plugin.yml, and if I pull this the command will change for everyone. If you want me to make the command customizable please suggest it and I might add it to the next update.

**Comment by esh123cookie** [comment]
> I know, it just doesn't make sense to change the command without changing the plugin.yml, and if I pull this the command will change for everyone. If you want me to make the command customizable please suggest it and I might add it to the next update.
Sure could you add it

**Comment by esh123cookie** [comment]
Yeah sure could you add it

**Comment by Todo56** [comment]
Custom command Feature has been added to the latest dev release https://poggit.pmmp.io/ci/Todo56/ShopUI/ShopUI

**Pull request closed without merging**
